INSERT INTO pokemon_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, card_number_in_collection, collection_set_id) VALUES 
(60, 'Charmander', 1, 1, 'Lizard Pokémon. It has a preference for hot things.', 'Ember', 30, 'Water', 'None', 1, 4, 1),
(70, 'Squirtle', 2, 1, 'Tiny Turtle Pokémon. It shelters itself in its shell, then strikes back with spouts of water at every opportunity.', 'Bubble', 20, 'Electric', 'None', 1, 7, 1),
(50, 'Bulbasaur', 3, 1, 'Seed Pokémon. A strange seed was planted on its back at birth.', 'Vine Whip', 20, 'Fire', 'None', 1, 1, 1),
(80, 'Pikachu', 4, 1, 'Mouse Pokémon. It keeps its tail raised to monitor its surroundings.', 'Thunder Shock', 30, 'Fighting', 'Metal', 1, 58, 2),
(80, 'Gyarados', 2, 3, 'Atrocious Pokémon. Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.', 'Dragon Rage', 50, 'Electric', 'None', 3, 6, 3),
(100, 'Dragonite', 4, 3, 'Dragon Pokémon. An extremely rare, intelligent, and powerful Pokémon.', 'Hyper Beam', 90, 'Ice', 'None', 3, 19, 3),
(70, 'Magmar', 1, 2, 'Spitfire Pokémon. It dislikes cold places, so it blows scorching flames to make the environment suitable.', 'Fire Punch', 40, 'Water', 'None', 2, 36, 1),
(90, 'Onix', 6, 1, 'Rock Snake Pokémon. As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.', 'Rock Throw', 30, 'Grass', 'None', 4, 56, 1),
(80, 'Alakazam', 5, 3, 'Psi Pokémon. Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.', 'Psychic', 50, 'Darkness', 'None', 3, 65, 4),
(60, 'Machop', 6, 1, 'Superpower Pokémon. It trains by lifting boulders.', 'Karate Chop', 20, 'Psychic', 'None', 2, 52, 4),
(90, 'Gengar', 5, 3, 'Shadow Pokémon. Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.', 'Shadow Punch', 60, 'Darkness', 'None', 3, 94, 3),
(100, 'Snorlax', 6, 1, 'Sleeping Pokémon. Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.', 'Body Slam', 80, 'Fighting', 'None', 4, 20, 3),
(70, 'Electabuzz', 4, 2, 'Electric Pokémon. Normally found near power plants, they can wander away and cause major blackouts in cities.', 'Thunder Punch', 50, 'Ground', 'None', 3, 44, 2),
(80, 'Hitmonlee', 6, 1, 'Kicking Pokémon. This amazing Pokémon has an awesome sense of balance. It can kick in succession from any position.', 'High Jump Kick', 60, 'Psychic', 'None', 2, 28, 2),
(50, 'Koffing', 6, 1, 'Poison Gas Pokémon. Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.', 'Tackle', 20, 'Psychic', 'None', 1, 42, 1),
(60, 'Jigglypuff', 9, 1, 'Balloon Pokémon. When it sings, it never pauses to breathe. It appears to be crying because its tears add to its character.', 'Double Slap', 20, 'Steel', 'None', 1, 39, 4),
(50, 'Pidgey', 6, 1, 'Tiny Bird Pokémon. A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.', 'Gust', 20, 'Electric', 'None', 1, 34, 1),
(80, 'Rhyhorn', 6, 1, 'Spikes Pokémon. Strong, but not too bright, this Pokémon can shatter even a skyscraper with its charging Tackles.', 'Horn Attack', 40, 'Grass', 'None', 4, 48, 3),
(90, 'Lapras', 2, 1, 'Transport Pokémon. A gentle soul that can ferry people across the sea on its back. It loves singing, though it is seldom heard.', 'Water Gun', 50, 'Electric', 'None', 4, 35, 4),
(100, 'Charizard', 1, 3, 'Flame Pokémon. Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.', 'Flamethrower', 70, 'Water', 'None', 3, 6, 1);
