INSERT INTO pokemon_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, card_number_in_collection, collection_set_id) VALUES 
(70, 'Oddish', 3, 1, 'Weed Pokémon. Its scientific name is Oddium Wanderus.', 'Absorb', 20, 'Fire', 'Water', 1, 43, 2),
(90, 'Cloyster', 2, 2, 'Bivalve Pokémon. When attacked, it launches its horns in quick volleys.', 'Spike Cannon', 30, 'Electric', 'None', 2, 16, 2),
(60, 'Exeggcute', 3, 1, 'Egg Pokémon. Often mistaken for eggs, they gather to form clusters.', 'Leech Seed', 20, 'Fire', 'Water', 1, 22, 3),
(100, 'Kangaskhan', 6, 1, 'Parent Pokémon. Raises its young in its belly pouch. Won’t run from any fight to keep its young protected.', 'Comet Punch', 60, 'Fighting', 'None', 3, 44, 4),
(80, 'Scyther', 3, 1, 'Mantis Pokémon. Leaps out of tall grass and slices its prey with its scythes.', 'Slash', 40, 'Fire', 'None', 1, 45, 2),
(90, 'Golem', 6, 2, 'Megaton Pokémon. Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'Rock Throw', 50, 'Water', 'None', 4, 41, 2),
(50, 'Grimer', 6, 1, 'Sludge Pokémon. Appears in filthy areas. Thrives by sucking up polluted sludge.', 'Pound', 20, 'Psychic', 'None', 2, 54, 3),
(100, 'Muk', 6, 2, 'Sludge Pokémon. Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.', 'Sludge', 60, 'Psychic', 'None', 3, 62, 2),
(80, 'Kabuto', 6, 1, 'Shellfish Pokémon. A Pokémon that was regenerated from a fossil found in what was once the ocean floor eons ago.', 'Scratch', 30, 'Electric', 'None', 2, 41, 1),
(50, 'Gastly', 5, 1, 'Gas Pokémon. Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.', 'Lick', 10, 'Darkness', 'None', 1, 36, 4),
(100, 'Gyarados', 2, 3, 'Atrocious Pokémon. Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.', 'Dragon Rage', 50, 'Electric', 'None', 3, 15, 3),
(90, 'Golduck', 2, 2, 'Duck Pokémon. Often seen swimming elegantly by lakeshores. It is often mistaken for the Japanese monster, Kappa.', 'Hydro Pump', 60, 'Electric', 'None', 2, 48, 2),
(60, 'Staryu', 2, 1, 'Star Shape Pokémon. As long as the center section is unharmed, it can grow back fully even if it is chopped to bits.', 'Water Gun', 20, 'Electric', 'None', 1, 39, 3),
(80, 'Starmie', 2, 2, 'Mysterious Pokémon. At the center of its body is a red core, which sends mysterious radio signals into the night sky.', 'Bubblebeam', 30, 'Electric', 'None', 2, 40, 3),
(100, 'Mew', 5, 1, 'New Species Pokémon. So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.', 'Psychic', 60, 'Darkness', 'None', 1, 151, 1),
(90, 'Vaporeon', 2, 2, 'Bubble Jet Pokémon. Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid’s.', 'Water Gun', 30, 'Electric', 'None', 2, 134, 4),
(70, 'Jolteon', 4, 2, 'Lightning Pokémon. It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts.', 'Thunder Shock', 40, 'Ground', 'None', 2, 135, 4),
(80, 'Flareon', 1, 2, 'Flame Pokémon. When storing thermal energy in its body, its temperature could soar to over 1600 degrees.', 'Flamethrower', 50, 'Water', 'None', 2, 136, 4),
(60, 'Porygon', 6, 1, 'Virtual Pokémon. A man-made Pokémon that came about as a result of research. It is programmed with only basic motions.', 'Conversion', 0, 'Fighting', 'None', 1, 137, 3),
(50, 'Omanyte', 2, 1, 'Spiral Pokémon. A Pokémon that was resurrected from a fossil. It lived in the sea for millions of years.', 'Water Gun', 20, 'Electric', 'None', 1, 138, 3),
(100, 'Omastar', 2, 2, 'Spiral Pokémon. A Pokémon that was resurrected from a fossil using modern science. It swam by cleverly twisting its 10 tentacles about.', 'Hydro Pump', 40, 'Electric', 'None', 3, 139, 3),
(70, 'Kabuto', 6, 1, 'Shellfish Pokémon. A Pokémon that was regenerated from a fossil found in what was once the ocean floor eons ago.', 'Scratch', 30, 'Electric', 'None', 2, 140, 1),
(90, 'Kabutops', 6, 2, 'Shellfish Pokémon. In battle, it uses its thick legs to clamber out of the water and execute powerful physical moves.', 'Hydro Pump', 40, 'Electric', 'None', 3, 141, 3),
(80, 'Aerodactyl', 6, 1, 'Fossil Pokémon. A ferocious, prehistoric Pokémon that goes for the enemy’s throat with its serrated, saw-like fangs.', 'Wing Attack', 30, 'Electric', 'None', 2, 142, 4),
(50, 'Snorlax', 6, 1, 'Sleeping Pokémon. Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.', 'Body Slam', 80, 'Fighting', 'None', 4, 143, 1),
(100, 'Articuno', 2, 3, 'Freeze Pokémon. A legendary bird Pokémon. It is said to appear to doomed people who are lost in icy mountains.', 'Ice Beam', 50, 'Steel', 'None', 3, 144, 3),
(80, 'Zapdos', 4, 3, 'Electric Pokémon. A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.', 'Thunder', 60, 'Rock', 'None', 4, 145, 1),
(90, 'Moltres', 1, 3, 'Flame Pokémon. A legendary bird Pokémon. As it flaps its flaming wings, even the night sky will turn red.', 'Fire Spin', 70, 'Electric', 'None', 4, 146, 3),
(60, 'Dratini', 6, 1, 'Dragon Pokémon. Long considered a mythical Pokémon until recently, when a small colony was found living underwater.', 'Wrap', 20, 'Dragon', 'None', 1, 147, 1),
(100, 'Dragonair', 6, 2, 'Dragon Pokémon. A mystical Pokémon that exudes a gentle aura. It can manipulate the elements as it wishes.', 'Dragon Rage', 40, 'Dragon', 'None', 3, 148, 1);