INSERT INTO pokemon_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, card_number_in_collection, collection_set_id) VALUES 
(70, 'Blastoise', 2, 3, 'Shellfish Pokémon. It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.', 'Hydro Pump', 50, 'Electric', 'None', 3, 2, 1),
(60, 'Butterfree', 3, 3, 'Butterfly Pokémon. In battle, it flaps its wings at high speed to release highly toxic dust into the air.', 'Whirlwind', 30, 'Electric', 'None', 2, 33, 2),
(70, 'Beedrill', 3, 3, 'Poison Bee Pokémon. Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.', 'Twineedle', 40, 'Fire', 'None', 1, 17, 2),
(60, 'Psyduck', 2, 1, 'Duck Pokémon. Always tormented by headaches. It uses psychic powers, but whether it intends to do so is not known.', 'Confusion', 20, 'Electric', 'None', 1, 53, 1),
(70, 'Growlithe', 1, 1, 'Puppy Pokémon. Very protective of its territory. It will bark and bite to repel intruders from its space.', 'Flame Wheel', 30, 'Water', 'None', 2, 54, 1),
(80, 'Arcanine', 1, 2, 'Legendary Pokémon. A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings.', 'Fire Blast', 50, 'Water', 'None', 3, 59, 1),
(50, 'Poliwag', 2, 1, 'Tadpole Pokémon. The swirl on its belly is its internal organs seen through its thin skin. It is better at swimming than walking.', 'Bubble', 20, 'Electric', 'None', 1, 25, 2),
(60, 'Abra', 5, 1, 'Psi Pokémon. Using its ability to read minds, it will identify impending danger and teleport to safety.', 'Teleport', 0, 'Darkness', 'None', 1, 32, 1),
(90, 'Rhydon', 6, 2, 'Drill Pokémon. Walks on its hind legs. Shows signs of intelligence. Its armor-like hide even repels molten lava.', 'Horn Drill', 60, 'Grass', 'None', 4, 56, 2),
(60, 'Farfetch’d', 6, 1, 'Wild Duck Pokémon. The plant stalk it holds is its weapon. The stalk is used like a sword to cut all sorts of things.', 'Slash', 30, 'Electric', 'None', 2, 45, 2),
(100, 'Mewtwo', 5, 3, 'Genetic Pokémon. A Pokémon created by recombining Mew’s genes. It’s said to have the most savage heart among Pokémon.', 'Psychic', 70, 'Darkness', 'None', 3, 10, 1),
(80, 'Kabutops', 6, 2, 'Shellfish Pokémon. Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.', 'Hydro Pump', 50, 'Electric', 'None', 3, 46, 3),
(50, 'Eevee', 9, 1, 'Evolution Pokémon. Its genetic code is irregular. It may mutate if it is exposed to radiation from elemental stones.', 'Tackle', 20, 'Fighting', 'None', 1, 51, 2),
(70, 'Ninetales', 1, 2, 'Fox Pokémon. It is said to live for 1,000 years. Its fur is said to be imbued with a mystical power.', 'Fire Spin', 40, 'Water', 'None', 2, 58, 1),
(60, 'Vulpix', 1, 1, 'Fox Pokémon. At the time of birth, it has just one tail. The tail splits from its tip as it grows older.', 'Ember', 20, 'Water', 'None', 1, 37, 2),
(90, 'Lapras', 2, 1, 'Transport Pokémon. A gentle soul that can ferry people across the sea on its back. It loves singing, though it is seldom heard.', 'Water Gun', 50, 'Electric', 'None', 4, 35, 4),
(70, 'Hitmonchan', 6, 1, 'Punching Pokémon. While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.', 'Mega Punch', 40, 'Psychic', 'None', 2, 47, 2),
(100, 'Articuno', 2, 3, 'Freeze Pokémon. A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.', 'Blizzard', 60, 'Steel', 'None', 4, 24, 3),
(60, 'Paras', 3, 1, 'Mushroom Pokémon. Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.', 'Scratch', 20, 'Fire', 'None', 1, 25, 1),
(80, 'Venomoth', 3, 2, 'Poison Moth Pokémon. The dust-like scales covering its wings are color-coded to indicate the kinds of poison it has.', 'Psychic', 40, 'Fire', 'None', 2, 22, 1),
(50, 'Meowth', 6, 1, 'Scratch Cat Pokémon. Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.', 'Bite', 20, 'Fighting', 'None', 1, 52, 2),
(70, 'Seel', 2, 1, 'Sea Lion Pokémon. The protruding horn on its head is very hard. It is used for bashing through thick ice.', 'Aurora Beam', 30, 'Electric', 'None', 3, 28, 4),
(100, 'Zapdos', 4, 3, 'Electric Pokémon. A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.', 'Thunder', 70, 'Rock', 'None', 4, 40, 1),
(90, 'Machamp', 6, 2, 'Superpower Pokémon. Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.', 'Cross Chop', 60, 'Psychic', 'None', 3, 15, 1),
(60, 'Pinsir', 6, 1, 'Stag Beetle Pokémon. If it fails to crush the victim in its pincers, it will swing it around and toss it hard.', 'Vice Grip', 30, 'Fire', 'None', 2, 49, 3),
(70, 'Tentacruel', 2, 2, 'Jellyfish Pokémon. Its 80 tentacles can stretch and contract freely. They wrap around prey and weaken it with poison.', 'Hydro Pump', 40, 'Electric', 'None', 3, 37, 2),
(80, 'Magneton', 4, 2, 'Magnet Pokémon. Formed by several Magnemites linked together. They frequently appear when sunspots flare up.', 'Thunder Wave', 50, 'Ground', 'None', 2, 42, 1),
(100, 'Moltres', 1, 3, 'Flame Pokémon. A legendary bird Pokémon. As it flaps its flaming wings, even the night sky will turn red.', 'Fire Spin', 70, 'Electric', 'None', 4, 30, 3),
(50, 'Ditto', 9, 1, 'Transform Pokémon. Capable of copying an opponent’s genetic code to instantly transform itself into a duplicate of the enemy.', 'Transform', 0, 'None', 'None', 1, 53, 2),
(70, 'Jynx', 5, 1, 'Human Shape Pokémon. Appears to move to a rhythm of its own, as if it were dancing. It wiggles its hips as it walks.', 'Ice Punch', 40, 'Steel', 'None', 3, 22, 1);
